### ISSUE TITLE
'Cannot enlarge memory arrays in asm.js.'

### ISSUE THREAD

**Issue by vladikoff** [tonyg/js-scrypt#1]
Hey,

Getting an error in the console:

_Cannot enlarge memory arrays in asm.js. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value, or (2) set Module.TOTAL_MEMORY before the program runs._

When using `crypto_scrypt`:

```
  var spass = scrypt.crypto_scrypt(
    scrypt.encode_utf8(payload.input),
   scrypt.encode_utf8(payload.salt),
    65536, 8, 1, 64)
```

I think the `65536` is at fault here (because if I change it to 16384 it works fine).
I'm going to try to rebuild the library as suggested in the error message. However might be useful for someone in the future to include some info about this in the README? 
Let me know your thoughts on the error.
Thanks!

**Comment by AntonLydike** [comment]
I am sorry, but I got the same error today. I tried cranking up `requested_total_memory` up to 2^30 bytes (1 Gigabyte) but even then I got the error. (I couldn't go higher, because after that I got the `Uncaught RangeError: Array buffer allocation failed` error).

Other than that I have the exact same error as above. I downloaded today (from browser/scrypt.js)

Do I need to recompile the whole thing with another parameter? Or is it just impossible to do scrypt with `n=1048576` in the browser?

**Comment by AntonLydike** [comment]
Never mind. I did a bit of testing, and came up with this table:

    you need:
     32MB = 33554432   = 2^25 to compute n up to = 2^14 = 16384
     64MB = 67108864   = 2^26 to compute n up to = 2^15 = 32768
    128MB = 134217728  = 2^27 to compute n up to = 2^16 = 65536
    256MB = 268435456  = 2^28 to compute n up to = 2^17 = 131072
    512MB = 536870912  = 2^29 to compute n up to = 2^18 = 262144
      1GB = 1073741824 = 2^30 to compute n up to = 2^19 = 524288

So for n=2^20 you'd need 2 Gigs of ram. Yeah. not gonna happen any time soon...

But it might be helpful to add this to the README.md

**Comment by tonyg** [comment]
Good idea -- @AntonLydike, would you be able to find the relevant section of the scrypt paper and draft something for inclusion in the README?

**Comment by AntonLydike** [comment]
@tonyq [this pdf](http://www.tarsnap.com/scrypt/scrypt.pdf)? or [these slides](http://www.tarsnap.com/scrypt/scrypt-slides.pdf)? or [this pdf](https://tools.ietf.org/pdf/rfc7914.pdf) from the RFC?

The RFC paper seems the best. It gave me this:

    The CPU/Memory cost parameter N ("costParameter") must be larger than 1, 
    a power of 2, and less than 2^(128 * r / 8).

but that isn't it. Then also:

    a large value of p can be used to increase the computational cost of scrypt
    without increasing the memory usage

but no answer, other than that `n` is the "cost" parameter. I ran another few tests. these are my results:

    n = 2^8  (= 256)    requires 2^20 (= 1048576)    bytes of ram
    n = 2^9  (= 512)    requires 2^20 (= 1048576)    bytes of ram
    n = 2^10 (= 1024)   requires 2^20 (= 1048576)    bytes of ram
    n = 2^11 (= 2048)   requires 2^20 (= 1048576)    bytes of ram
    n = 2^12 (= 4096)   requires 2^20 (= 1048576)    bytes of ram
    n = 2^13 (= 8192)   requires 2^20 (= 1048576)    bytes of ram
    n = 2^14 (= 16384)  requires 2^25 (= 33554432)   bytes of ram
    n = 2^15 (= 32768)  requires 2^26 (= 67108864)   bytes of ram
    n = 2^16 (= 65536)  requires 2^27 (= 134217728)  bytes of ram
    n = 2^17 (= 131072) requires 2^28 (= 268435456)  bytes of ram
    n = 2^18 (= 262144) requires 2^29 (= 536870912)  bytes of ram
    n = 2^19 (= 262144) requires 2^30 (= 1073741824) bytes of ram

I imagine that 2^20 stays like this, because there is a lower limit (I got a console.warn `increasing TOTAL_MEMORY to 16777216 to be compliant with the asm.js spec (and given that TOTAL_STACK=5242880)`)

A quick plot shows, that all in all it seems like linear growth:

![ram for n](https://cloud.githubusercontent.com/assets/14147713/21164451/43fd96d0-c199-11e6-8b1a-e8717b2ee264.png)

So I assume, that you'd need 2 GB for n to be the recommended 2^20 (when hashing files)...

Should I just fork, explain this a little bit nicer and then do a pull request? (I'm a bit new to git :smile:)

**Comment by tonyg** [comment]
@AntonLydike that sounds great! Yes, a fork-and-PR would be brilliant. Thanks for digging into this.

**Comment by tonyg** [comment]
For the record, PR #27 (merged just now) includes good documentation from Anton on configuring memory.
